[package]
name = "sourcemap"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.8", features = ["full", "extra-traits"] }
proc-macro2 = { version = "1.0.6", features = ["span-locations", "nightly"] }

